// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqfbgfjmprwxfjatlxhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxZmJnZmptcHJ3eGZqYXRseGhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjg5NTEsImV4cCI6MjA3MTk0NDk1MX0.JR6vB_C7GvPXzB_Rrlg7YlcoYtPQx510q2fa_E8_PmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});